# 测试平台默认数据库链接信息.内网（阿里云）
datasource.url.automation=jdbc:mysql://hp-polar-test-business-master.mysql.polardb.rds.aliyuncs.com:3306/automation_test?allowPublicKeyRetrieval=true
datasource.username.automation=automation
datasource.password.automation=20AR@UJsobwLBdih

# 测试用例默认数据库链接信息，panda_test
datasource.url.panda_test=jdbc:mysql://hp-polar-test-business-master.mysql.polardb.rds.aliyuncs.com:3306/panda_test?allowPublicKeyRetrieval=true
datasource.username.panda_test=panda_test
datasource.password.panda_test=Pan$te19*

# #########################################      以下是业务测试数据   ###################################################
pos.account.of.public.password=Test123456


