#spring log
logging.level.org.springframework.boot.autoconfigure=error
spring.profiles.active=test
# 用于控制是否保存自动化测试执行记录、测试用例执行次数，会影响测试用例的 ROI 统计。调试时设置为 true，默认值false，不配置也是false。
framework.is.debug.testcase=false