#spring log
logging.level.org.springframework.boot.autoconfigure=error
spring.profiles.active=test

# 是否不保存自动化测试执行记录到数据库表中的开关。默认值 false 代表上传，会把执行记录保存到数据库中，会影响测试用例的 ROI 统计。设置为 true 则不上报。
framework.is.not.save.automation.execution.record=false