#spring log
logging.level.org.springframework.boot.autoconfigure=error
spring.profiles.active=test

# 是否保存自动化测试执行记录到数据库表中的开关。调试时设置为 false， 设置为 true 则会把执行记录保存到数据库中，会影响测试用例的 ROI 统计。
framework.is.save.automation.execution.record=true