spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-3ns24734o9z8747d0.mysql.rds.aliyuncs.com:3306/fresh_test?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false&serverTimezone=GMT%2B8
spring.datasource.username=PF@_GSkFnRGA/BiqRecDkGlmHw==
spring.datasource.password=PF@_oTN6Y5Dp8jj1W2A9t20mQfbeK9xEM/Vp

fresh.env.domain=https://test.pandafreshmart.com
