# 指定默认加载的配置文件
spring.profiles.active=test
#配置服务的端口，默认8080
server.port=9080
server.servlet.context-path=/api
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8


spring.main.allow-circular-references=true

#逻辑删除配置
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

# mybatis-plus配置Mapper.xml文件的路径，注意官网说多模块的化需要使用classpath*开头
mybatis-plus.mapper-locations=classpath*:miller/mapper/*Mapper.xml

# 实体路径名称，这样配置之后就在resultType中可以不需要输入全路径
mybatis-plus.type-aliases-package=com.miller.entity
# 开启驼峰风格转化，需要注意的是如果使用MyBatis-plus的这个配置之后，不要在mybatis-config.xml重复配置
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 开启延迟加载/懒加载
mybatis-plus.configuration.lazy-loading-enabled=true
# 配置按需加载
mybatis-plus.configuration.aggressive-lazy-loading=false
# 使用主键
mybatis-plus.configuration.use-generated-keys=true
# 指定日志级别
logging.level.root=info
logging.level.com.miller.mapper=trace
logging.pattern.console=[%p] %m%n

# swagger配置，生产一般关闭
#springfox.documentation.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# flyway 数据库版本管理工具配置
# flyway.enabled=true则启用，所有配置生效，=false则所有配置不生效，也不会执行migration目录下的脚本
spring.flyway.enabled=true
# 设置为 true 在需要 baseline 的时候,自动执行一次 baseline。
spring.flyway.baseline-on-migrate=true
# 验证版本是否符合逻辑，比如先执行了 DML 而没有 对应的 DDL 会抛出异常
spring.flyway.validate-on-migrate=false
# 执行日志
logging.level.org.flywaydb=debug
# flyway migration 存放得文件夹路径
spring.flyway.locations=classpath:db/migration
# flyway 版本管理表
spring.flyway.table=flyway_schema_history
# 基线版本
spring.flyway.baseline-version=1
spring.flyway.encoding=UTF-8
