# flyway <= 7.15.0 版本不兼容H2的最新版本，所以这里使用H2的时候禁用掉flyway，使用spring.sql.init.schema-locations方式
# 执行db/migration目录下的*.sql文件。如果使用 flyway >=7.15.0版本则兼容H2，但 MySQL 版本必须大于5.7
spring.flyway.enabled=false
# 配置H2内存数据库
spring.datasource.driver-class-name=org.h2.Driver
# 使用spring的初始化脚本执行SQL语句。推荐使用flyway默认目录保证测试是SQL脚本是最新的，
spring.sql.init.schema-locations=classpath*:db/migration/*.sql
# 如果需要独立的测试数据可以启用下面的配置
spring.sql.init.data-locations=classpath*:db/test_data.sql
# 使用mem内存数据库，进程结束自动销毁数据.兼容MySQL语法MODE=MYSQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER
spring.datasource.url=jdbc:h2:mem:ct_dev;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER
spring.datasource.username=root
spring.datasource.password=
