# \u6307\u5B9A\u9ED8\u8BA4\u52A0\u8F7D\u7684\u914D\u7F6E\u6587\u4EF6
spring.profiles.active=test
#\u914D\u7F6E\u670D\u52A1\u7684\u7AEF\u53E3\uFF0C\u9ED8\u8BA48080
server.port=9080
server.servlet.context-path=/api
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8


spring.main.allow-circular-references=true

#\u903B\u8F91\u5220\u9664\u914D\u7F6E
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

# mybatis-plus\u914D\u7F6EMapper.xml\u6587\u4EF6\u7684\u8DEF\u5F84\uFF0C\u6CE8\u610F\u5B98\u7F51\u8BF4\u591A\u6A21\u5757\u7684\u5316\u9700\u8981\u4F7F\u7528classpath*\u5F00\u5934
mybatis-plus.mapper-locations=classpath*:miller/mapper/*Mapper.xml

# \u5B9E\u4F53\u8DEF\u5F84\u540D\u79F0\uFF0C\u8FD9\u6837\u914D\u7F6E\u4E4B\u540E\u5C31\u5728resultType\u4E2D\u53EF\u4EE5\u4E0D\u9700\u8981\u8F93\u5165\u5168\u8DEF\u5F84
mybatis-plus.type-aliases-package=com.miller.entity
# \u5F00\u542F\u9A7C\u5CF0\u98CE\u683C\u8F6C\u5316\uFF0C\u9700\u8981\u6CE8\u610F\u7684\u662F\u5982\u679C\u4F7F\u7528MyBatis-plus\u7684\u8FD9\u4E2A\u914D\u7F6E\u4E4B\u540E\uFF0C\u4E0D\u8981\u5728mybatis-config.xml\u91CD\u590D\u914D\u7F6E
mybatis-plus.configuration.map-underscore-to-camel-case=true
# \u5F00\u542F\u5EF6\u8FDF\u52A0\u8F7D/\u61D2\u52A0\u8F7D
mybatis-plus.configuration.lazy-loading-enabled=true
# \u914D\u7F6E\u6309\u9700\u52A0\u8F7D
mybatis-plus.configuration.aggressive-lazy-loading=false
# \u4F7F\u7528\u4E3B\u952E
mybatis-plus.configuration.use-generated-keys=true
# \u6307\u5B9A\u65E5\u5FD7\u7EA7\u522B
logging.level.root=info
logging.level.com.miller.mapper=trace
logging.pattern.console=[%p] %m%n

# swagger\u914D\u7F6E\uFF0C\u751F\u4EA7\u4E00\u822C\u5173\u95ED
#springfox.documentation.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# flyway 数据库版本管理工具配置
# flyway.enabled=true则启用，所有配置生效，=false则所有配置不生效，也不会执行migration目录下的脚本
spring.flyway.enabled=true
# 设置为 true 在需要 baseline 的时候,自动执行一次 baseline。
spring.flyway.baseline-on-migrate=true
# 验证版本是否符合逻辑，比如先执行了 DML 而没有 对应的 DDL 会抛出异常
spring.flyway.validate-on-migrate=false
# 执行日志
logging.level.org.flywaydb=debug
# flyway migration 存放得文件夹路径
spring.flyway.locations=classpath:db/migration
# flyway 版本管理表
spring.flyway.table=flyway_schema_history
# 基线版本
spring.flyway.baseline-version=1
spring.flyway.encoding=UTF-8
