# 指定默认加载的配置文件
spring.profiles.active=test
#配置服务的端口，默认8080
server.port=9080
server.servlet.context-path=/api
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8



spring.main.allow-circular-references=true

#逻辑删除配置
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0

# mybatis-plus配置Mapper.xml文件的路径，注意官网说多模块的化需要使用classpath*开头
mybatis-plus.mapper-locations=classpath*:miller/mapper/*Mapper.xml

# 实体路径名称，这样配置之后就在resultType中可以不需要输入全路径
mybatis-plus.type-aliases-package=com.miller.entity
# 开启驼峰风格转化，需要注意的是如果使用MyBatis-plus的这个配置之后，不要在mybatis-config.xml重复配置
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 开启延迟加载/懒加载
mybatis-plus.configuration.lazy-loading-enabled=true
# 配置按需加载
mybatis-plus.configuration.aggressive-lazy-loading=false
# 使用主键
mybatis-plus.configuration.use-generated-keys=true
# 指定日志级别
logging.level.root=info
logging.level.com.miller.mapper=trace
logging.pattern.console=[%p] %m%n

# swagger配置，生产一般关闭
#springfox.documentation.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
# 关闭多数据源，否则会扫描报错，请勿修改
spring.datasource.dynamic.enabled=false