# 生产环境 数据库连接信息。修改请慎重。内网（香港云）
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-3ns24734o9z8747d0.mysql.rds.aliyuncs.com:3306/automation_test
spring.datasource.username=automation
spring.datasource.password=20AR@UJsobwLBdih

# #########################################      以下是业务测试数据   ###################################################

# 测试用例默认数据库链接信息，panda_test
datasource.url.panda_test=jdbc:mysql://rm-3ns24734o9z8747d0.mysql.rds.aliyuncs.com:3306/panda_test
datasource.username.panda_test=panda_test
datasource.password.panda_test=Pan$te19*