# 测试环境 数据库连接信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-3ns24734o9z8747d0jo.mysql.rds.aliyuncs.com:3306/panda_test
spring.datasource.username=panda_test
spring.datasource.password=Pan$te19*
#支付中心库
spring.datasource.pay.url=jdbc:mysql://rm-3ns24734o9z8747d0jo.mysql.rds.aliyuncs.com:3306/pandapay_test
# #########################################      以下是业务测试数据   ###################################################
# 统一登陆的密码
user.app.account.of.public.password=Test123456
user.app.account.of.public.login.type=2
# user002 是默认用户,用于测试订单主流程
user.app.account.of.user002.account.callingCode=86
user.app.account.of.user002.account=18711110002
user.app.account.of.user002.account.id=1398708422
# 设备号
user.app.account.of.user002.account.distinctId=44d6884fdb174a78

#支付中心测试站域名
pay.server.notification.app.url.domain=https://hz-test-pay.hungrypanda.cn
#配送距离转换单位
user.app.server.metric.unit=km

# 定时任务Job配置
# 定时任务：搜索索引更新服务
user.app.job.increment.index.update.id=11
user.app.job.increment.shop.index.update.id=470

########################################## 商卡二期测试数据-Start ##########################################
user.app.for.test.shop.card.version2.shopId=387549545
user.app.for.test.shop.card.version2.shopAccount=18722220010
user.app.for.test.shop.card.version2.shopPassword=415664VSC

user.app.for.test.shop.card.version2.02.shopId=669770737
user.app.for.test.shop.card.version2.blank.compare.shopId=160288176
# 商卡测试新人账号
user.app.account.for.shop.card.version2.new.user.account=13999900001
user.app.account.for.shop.card.version2.new.user.password=123456
user.app.account.for.shop.card.version2.new.user.account.id=1398712902


# 熊猫联盟满减券测试账号
user.app.account.for.shop.card.version2.pandaFull.user.account=17000001111
user.app.account.for.shop.card.version2.pandaFull.user.password=111111
user.app.account.for.shop.card.version2.pandaFull.user.account.id=1398713048
# 熊猫联盟折扣券测试账号
user.app.account.for.shop.card.version2.pandaDiscount.user.account=17000001112
user.app.account.for.shop.card.version2.pandaDiscount.user.password=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id=1398713050
# 熊猫联盟XMLM02折扣券测试账号
user.app.account.for.shop.card.version2.pandaDiscount.user.account.xmlm02=17000001113
user.app.account.for.shop.card.version2.pandaDiscount.user.password.xmlm02=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id.xmlm02=1398713062
# 无任何优惠券测试账号
user.app.account.for.shop.card.version2.no.coupon.user.account=17000001114
user.app.account.for.shop.card.version2.no.coupon.user.password=111111
user.app.account.for.shop.card.version2.no.coupon.user.account.id=1398713128

user.app.for.test.shop.card.version2.pickup.discountSn=545257587K
user.app.for.test.shop.card.version2.takeout.discountSn=5452C0FN0T
user.app.for.test.shop.card.version2.shop.new.user.discountSn=5452LGZTXY
user.app.for.test.shop.card.version2.voucherSn=54522NRAFJ
user.app.for.test.shop.card.version2.shop.first.discount.id=338

#会员用户
user.app.account.for.shop.card.version2.member.account=17048460001
user.app.account.for.shop.card.version2.member.password=123456a
user.app.account.for.shop.card.version2.member.cityname=九江市

#会员城市ID
user.app.for.test.shop.card.version2.memberCityId=1111378
#店铺会员红包-店铺联盟券红包ID
user.app.for.test.shop.card.version2.shop.redPacketId=888890374



########################################## 商卡二期测试数据-Stop # #########################################

# #########################################      panjuxiang个人测试数据   ###################################################
user.app.account.of.user.pjx.account=13990000001
user.app.account.of.user.pjx.password=123456
user.app.account.of.user.pjx.account.id=1398710856
user.app.index.banner.index.module.detailId.type1=103457824
user.app.index.banner.index.module.detailId.type2=103458130
user.app.index.banner.index.module.detailId.type3=103457822
user.app.index.banner.index.module.detailId.type4=103458134
user.app.index.banner.index.module.detailId.type5=103458136
user.app.index.banner.index.module.detailId.type6=103458132
user.app.index.banner.index.module.detailId.type13=103458138
user.app.index.banner.index.module.detailId.type18=103457826
user.app.index.banner.index.module.detailId.type20=103458142
user.app.index.banner.index.module.detailId.type23=103458140
user.app.index.banner.index.module.detailId.oldUser=103458196
user.app.index.banner.index.module.detailId.newUser=103458194
