# 测试平台默认数据库链接信息.外网（阿里云）
datasource.url.automation=jdbc:mysql://hp-polar-test-business-master-pub.mysql.polardb.rds.aliyuncs.com:3306/automation_test?allowPublicKeyRetrieval=true
datasource.username.automation=automation
datasource.password.automation=20AR@UJsobwLBdih

# 测试用例默认数据库链接信息，panda_test
datasource.url.panda_test=jdbc:mysql://hp-polar-test-business-master-pub.mysql.polardb.rds.aliyuncs.com:3306/panda_test?allowPublicKeyRetrieval=true
datasource.username.panda_test=panda_test
datasource.password.panda_test=Pan$te19*

# 支付中心库
datasource.url.pay=jdbc:mysql://hp-polar-test-business-master-pub.mysql.polardb.rds.aliyuncs.com:3306/pandapay_test
datasource.username.pay=panda_test
datasource.password.pay=Pan$te19*

# Redis
spring.data.redis.host=r-3nscqny4art27v9hrzpd.redis.rds.aliyuncs.com
spring.data.redis.port=6379
spring.data.redis.password=YNKAthEbNF3XoK8E

# #########################################      以下是业务测试数据   ###################################################
# 统一登陆的密码
user.app.account.of.public.password=123456
user.app.account.of.public.login.type=2
# user002 是默认用户,用于测试订单主流程
user.app.account.of.user002.account.callingCode=86
user.app.account.of.user002.account=18711110002
user.app.account.of.user002.account.id=1398708422
# 设备号
user.app.account.of.user002.account.distinctId=ed99f8b03a64c6c1

#支付中心测试站域名
pay.server.notification.app.url.domain=https://hz-test-pay.hungrypanda.cn
#配送距离转换单位
user.app.server.metric.unit=km

# 定时任务Job配置
# 定时任务：搜索索引更新服务
user.app.job.increment.index.update.id=11
user.app.job.increment.shop.index.update.id=470

#城市id 九江
user.app.auto.test.city.id=508

########################################## 商卡二期测试数据-Start ##########################################
user.app.for.test.shop.card.version2.shopId=387549545
user.app.for.test.shop.card.version2.shopAccount=18722220010
user.app.for.test.shop.card.version2.shopPassword=415664VSC

user.app.for.test.shop.card.version2.02.shopId=669770737
user.app.for.test.shop.card.version2.blank.compare.shopId=160288176
user.app.for.test.shop.card.version2.04.shopId=863876353
user.app.for.test.shop.card.version2.blank.02.compare.shopId=54329731
user.app.for.test.shop.card.version2.03.shopId=288825672
# 商卡测试新人账号
# 该账号目前已是非新人账号
user.app.account.for.shop.card.version2.new.user.account=13999900001
user.app.account.for.shop.card.version2.new.user.password=123456
user.app.account.for.shop.card.version2.new.user.account.id=1398712902

user.app.account.for.shop.card.version2.new.user02.account=13999900003
user.app.account.for.shop.card.version2.new.user02.password=123456
user.app.account.for.shop.card.version2.new.user02.account.id=1398715012

user.app.account.for.shop.card.version2.new.user03.account=13999900002
user.app.account.for.shop.card.version2.new.user03.password=123456
user.app.account.for.shop.card.version2.new.user03.account.id=1398712910

user.app.account.for.shop.card.version2.new.user04.account=13999900004
user.app.account.for.shop.card.version2.new.user04.password=123456
user.app.account.for.shop.card.version2.new.user04.account.id=1398717234


# 熊猫联盟满减券测试账号
user.app.account.for.shop.card.version2.pandaFull.user.account=17000001111
user.app.account.for.shop.card.version2.pandaFull.user.password=111111
user.app.account.for.shop.card.version2.pandaFull.user.account.id=1398713048
# 熊猫联盟折扣券测试账号
user.app.account.for.shop.card.version2.pandaDiscount.user.account=17000001112
user.app.account.for.shop.card.version2.pandaDiscount.user.password=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id=1398713050
# 熊猫联盟XMLM02折扣券测试账号
user.app.account.for.shop.card.version2.pandaDiscount.user.account.xmlm02=17000001113
user.app.account.for.shop.card.version2.pandaDiscount.user.password.xmlm02=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id.xmlm02=1398713062
# 无任何优惠券测试账号
user.app.account.for.shop.card.version2.no.coupon.user.account=17000001114
user.app.account.for.shop.card.version2.no.coupon.user.password=111111
user.app.account.for.shop.card.version2.no.coupon.user.account.id=1398713128
#会员用户
user.app.account.for.member.order.user.account=17000001115
user.app.account.for.member.order.user.password=111111
user.app.account.for.member.order.user.account.id=1398715264

user.app.for.test.shop.card.version2.pickup.discountSn=545257587K
user.app.for.test.shop.card.version2.takeout.discountSn=5452C0FN0T
user.app.for.test.shop.card.version2.shop.new.user.discountSn=5452LGZTXY
user.app.for.test.shop.card.version2.voucherSn=54522NRAFJ
user.app.for.test.shop.card.version2.shop.first.discount.id=338

#会员用户
user.app.account.for.shop.card.version2.member.account=17048460003
user.app.account.for.shop.card.version2.member.password=123456a
user.app.account.for.shop.card.version2.member.cityname=九江市

#会员城市ID
user.app.for.test.shop.card.version2.memberCityId=1111378
#店铺会员红包-店铺联盟券红包ID
user.app.for.test.shop.card.version2.shop.redPacketId=888892732

#新人首单标签人群账号
user.app.account.for.shop.card.version2.first.order.user.password=123456
user.app.account.for.shop.card.version2.first.order.user.account1=15100000021
user.app.account.for.shop.card.version2.first.order.user.userId1=1398713060
user.app.account.for.shop.card.version2.first.order.user.account2=15100000022
user.app.account.for.shop.card.version2.first.order.user.userId2=1398713064
#新人首单标签人群设备
user.app.account.for.shop.card.version2.first.order.user.distinctId=d88a89d4913c70bd
user.app.account.for.shop.card.version2.first.order.user.distinctId2=d88a89d4913c70be

#招商计划id
user.app.for.test.shop.card.version2.invitation.activity.id=1698

#自动化测试店铺商家标签
user.app.for.test.shop.card.version2.shop.category.id=[5946]
#商卡营业状态测试店铺信息
user.app.for.test.shop.card.version2.shopId.close=345263066
user.app.for.test.shop.card.version2.shopId.stop.order=617846488
#商卡可预约状态店铺
user.app.for.test.shop.card.version2.open.pre=855828829
user.app.for.test.shop.card.version2.open.no.pre=221864167
user.app.for.test.shop.card.version2.close.pre=422389118
user.app.for.test.shop.card.version2.close.no.pre=335765650

#商卡红包标签测试（SKYX实验组）
#店铺红包商家 ID
user.app.for.test.shop.card.version3.shopId=456846660
#满减加码商家ID
user.app.for.test.shop.card.version3.increase.shopId=829805751
#折扣加码商家ID
user.app.for.test.shop.card.version3.increase.discount.shopId=768477723
#有红包的账号
user.app.for.test.shop.card.version3.account=19286819216
user.app.for.test.shop.card.version3.password=12345678
user.app.for.test.shop.card.version3.userId=1398717855
#神券红包Id
user.app.for.test.shop.card.version3.redpacketId=888893280
#联盟满减券id
user.app.for.test.shop.card.version3.redpacketId2=888895652
#联盟折扣券id
user.app.for.test.shop.card.version3.redpacketId3=888895653
#普通满减券红包id
user.app.for.test.shop.card.version3.redpacketId4=888895549
#普通折扣券红包id
user.app.for.test.shop.card.version3.redpacketId5=888895655


########################################## 商卡二期测试数据-Stop # #########################################

# #########################################      panjuxiang个人测试数据   ###################################################
user.app.account.of.user.pjx.account=13990000001
user.app.account.of.user.pjx.password=123456
user.app.account.of.user.pjx.account.id=1398710856
user.app.index.banner.index.module.detailId.type1=103457824
user.app.index.banner.index.module.detailId.type2=103458130
user.app.index.banner.index.module.detailId.type3=103457822
user.app.index.banner.index.module.detailId.type4=103458134
user.app.index.banner.index.module.detailId.type5=103458136
user.app.index.banner.index.module.detailId.type6=103458132
user.app.index.banner.index.module.detailId.type13=103458138
user.app.index.banner.index.module.detailId.type18=103457826
user.app.index.banner.index.module.detailId.type20=103458142
user.app.index.banner.index.module.detailId.type23=103458140
user.app.index.banner.index.module.detailId.oldUser=103458196
user.app.index.banner.index.module.detailId.newUser=103458194

user.app.for.test.shop.card.version2.highSaleNoTop10.shopId=772457447


user.app.game.newUser.account=13990000005
user.app.game.oldUser.account=13990000006
user.app.game.memberUser.account=13990000007
user.app.game.user.common.password=123456
user.app.game.sn01=4TuuyGqDa2tw


user.app.login.device.id = auto-test-device-id


# 测试预算关联的预算活动sn
user.app.game.redPacket.activitySn.01=42528O72RJ

user.app.game.prizesId.redPacket.expire=6696
user.app.game.prizesId.redPacket.cancel=6698
user.app.game.prizesId.redPacket.noStock=6716
user.app.game.prizesId.redPacket.budgetBreak=6722
user.app.game.prizesId.redPacket.prizes.noStock=6724

#杨勤勤测试数据
#有会员神券用户
user.app.account.for.shop.card.version2.godCoupon.account=17048460002
user.app.account.for.shop.card.version2.godCoupon.password=123456a
user.app.account.for.shop.card.version2.godCoupon.distinctId=ed99f8b03a64c6c1

#严灿灿测试数据
#普通计划账号
user.app.account.activity.user01.account=17700000002
user.app.account.activity.user01.password=123456
user.app.account.activity.user01.userId=140397134
#强推计划账号
user.app.account.activity.user02.account=17700000001
user.app.account.activity.user02.password=123456
user.app.account.activity.user02.userId=1398661342
#智能营销账号
user.app.account.activity.user03.account=17700000077
user.app.account.activity.user03.password=123456
user.app.account.activity.user03.userId=1398716814
