# #########################################      命名约定规范   ########################################################
# 1. 如果已知 spring 有相关配置项，则默认名称使用 spring 提供的配置项名称，如 spring.datasource.url
# 2. 如果是自定义的配置项，则尽量区分业务领，如 demo.env.domain。第一位为代码工程模块名称，第二位为业务域模块名称，第N位为配置项名称
# 3. 【重要】重名称key时必须使用 IDE 提供的重命名功能，避免修改仅配置文件生效，代码中未自动修改。
# 4. 配置项名称使用小驼峰命名法，如 demo.user.password.default
# 5. 配置项长度无限制，尽量表达出配置项的含义，可以长一些，如:demo.user.account.password.default; userapp.order.create.by.platform.delivery
# #########################################      命名约定规范   ########################################################

# 默认配置文件
# 选择需要激活的配置文件，多个配置文件时会先加载默认配置文件，然后在加载 spring.profiles.active 指定的配置文件，相同的配置项会覆盖默认配置文件
spring.profiles.active=test
# 测试用例数据文件路径，默认为 testdata
testcase.data.file.path=testdata

# 用于控制是否保存自动化测试执行记录、测试用例执行次数，会影响测试用例的 ROI 统计。调试时设置为 true，默认值false，不配置也是false。
# framework.is.debug.testcase=true