# #########################################      \u547D\u540D\u7EA6\u5B9A\u89C4\u8303   ########################################################
# 1. \u5982\u679C\u5DF2\u77E5 spring \u6709\u76F8\u5173\u914D\u7F6E\u9879\uFF0C\u5219\u9ED8\u8BA4\u540D\u79F0\u4F7F\u7528 spring \u63D0\u4F9B\u7684\u914D\u7F6E\u9879\u540D\u79F0\uFF0C\u5982 spring.datasource.url
# 2. \u5982\u679C\u662F\u81EA\u5B9A\u4E49\u7684\u914D\u7F6E\u9879\uFF0C\u5219\u5C3D\u91CF\u533A\u5206\u4E1A\u52A1\u9886\uFF0C\u5982 demo.env.domain\u3002\u7B2C\u4E00\u4F4D\u4E3A\u4EE3\u7801\u5DE5\u7A0B\u6A21\u5757\u540D\u79F0\uFF0C\u7B2C\u4E8C\u4F4D\u4E3A\u4E1A\u52A1\u57DF\u6A21\u5757\u540D\u79F0\uFF0C\u7B2CN\u4F4D\u4E3A\u914D\u7F6E\u9879\u540D\u79F0
# 3. \u3010\u91CD\u8981\u3011\u91CD\u540D\u79F0key\u65F6\u5FC5\u987B\u4F7F\u7528 IDE \u63D0\u4F9B\u7684\u91CD\u547D\u540D\u529F\u80FD\uFF0C\u907F\u514D\u4FEE\u6539\u4EC5\u914D\u7F6E\u6587\u4EF6\u751F\u6548\uFF0C\u4EE3\u7801\u4E2D\u672A\u81EA\u52A8\u4FEE\u6539\u3002
# 4. \u914D\u7F6E\u9879\u540D\u79F0\u4F7F\u7528\u5C0F\u9A7C\u5CF0\u547D\u540D\u6CD5\uFF0C\u5982 demo.user.password.default
# 5. \u914D\u7F6E\u9879\u957F\u5EA6\u65E0\u9650\u5236\uFF0C\u5C3D\u91CF\u8868\u8FBE\u51FA\u914D\u7F6E\u9879\u7684\u542B\u4E49\uFF0C\u53EF\u4EE5\u957F\u4E00\u4E9B\uFF0C\u5982:demo.user.account.password.default; userapp.order.create.by.platform.delivery
# #########################################      \u547D\u540D\u7EA6\u5B9A\u89C4\u8303   ########################################################

# \u9ED8\u8BA4\u914D\u7F6E\u6587\u4EF6
# \u9009\u62E9\u9700\u8981\u6FC0\u6D3B\u7684\u914D\u7F6E\u6587\u4EF6\uFF0C\u591A\u4E2A\u914D\u7F6E\u6587\u4EF6\u65F6\u4F1A\u5148\u52A0\u8F7D\u9ED8\u8BA4\u914D\u7F6E\u6587\u4EF6\uFF0C\u7136\u540E\u5728\u52A0\u8F7D spring.profiles.active \u6307\u5B9A\u7684\u914D\u7F6E\u6587\u4EF6\uFF0C\u76F8\u540C\u7684\u914D\u7F6E\u9879\u4F1A\u8986\u76D6\u9ED8\u8BA4\u914D\u7F6E\u6587\u4EF6
spring.profiles.active=@activatedProperties@
# \u6D4B\u8BD5\u7528\u4F8B\u6570\u636E\u6587\u4EF6\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u4E3A testdata
testcase.data.file.path=testdata

# \u7528\u4E8E\u63A7\u5236\u662F\u5426\u4FDD\u5B58\u81EA\u52A8\u5316\u6D4B\u8BD5\u6267\u884C\u8BB0\u5F55\u3001\u6D4B\u8BD5\u7528\u4F8B\u6267\u884C\u6B21\u6570\uFF0C\u4F1A\u5F71\u54CD\u6D4B\u8BD5\u7528\u4F8B\u7684 ROI \u7EDF\u8BA1\u3002\u8C03\u8BD5\u65F6\u8BBE\u7F6E\u4E3A true\uFF0C\u9ED8\u8BA4\u503Cfalse\uFF0C\u4E0D\u914D\u7F6E\u4E5F\u662Ffalse\u3002
# framework.is.debug.testcase=true



# #########################################      \u4EE5\u4E0B\u662F\u4E1A\u52A1\u6D4B\u8BD5\u6570\u636E   ###################################################
# \u7EDF\u4E00\u767B\u9646\u7684\u5BC6\u7801
user.app.account.of.public.password=123456
user.app.account.of.public.login.type=2
# user002 \u662F\u9ED8\u8BA4\u7528\u6237,\u7528\u4E8E\u6D4B\u8BD5\u8BA2\u5355\u4E3B\u6D41\u7A0B
user.app.account.of.user002.account.callingCode=86
user.app.account.of.user002.account=18711110002
user.app.account.of.user002.account.id=1398708422
# \u8BBE\u5907\u53F7
user.app.account.of.user002.account.distinctId=ed99f8b03a64c6c1

#\u652F\u4ED8\u4E2D\u5FC3\u6D4B\u8BD5\u7AD9\u57DF\u540D
pay.server.notification.app.url.domain=https://hz-test-pay.hungrypanda.cn
#\u914D\u9001\u8DDD\u79BB\u8F6C\u6362\u5355\u4F4D
user.app.server.metric.unit=km

# \u5B9A\u65F6\u4EFB\u52A1Job\u914D\u7F6E
# \u5B9A\u65F6\u4EFB\u52A1\uFF1A\u641C\u7D22\u7D22\u5F15\u66F4\u65B0\u670D\u52A1
user.app.job.increment.index.update.id=11
user.app.job.increment.shop.index.update.id=470
#\u65B0\u63A8\u8350
user.app.job.increment.shop.index.update.new.id=620
#\u57CE\u5E02id \u4E5D\u6C5F
user.app.auto.test.city.id=508

########################################## \u5546\u5361\u4E8C\u671F\u6D4B\u8BD5\u6570\u636E-Start ##########################################
user.app.for.test.shop.card.version2.shopId=387549545
user.app.for.test.shop.card.version2.shopAccount=18722220010
user.app.for.test.shop.card.version2.shopPassword=415664VSC


user.app.for.test.shop.card.version2.02.shopId=669770737
user.app.for.test.shop.card.version2.blank.compare.shopId=160288176
user.app.for.test.shop.card.version2.04.shopId=863876353
user.app.for.test.shop.card.version2.blank.02.compare.shopId=54329731
user.app.for.test.shop.card.version2.03.shopId=288825672
# \u5546\u5361\u6D4B\u8BD5\u65B0\u4EBA\u8D26\u53F7
# \u8BE5\u8D26\u53F7\u76EE\u524D\u5DF2\u662F\u975E\u65B0\u4EBA\u8D26\u53F7
user.app.account.for.shop.card.version2.new.user.account=13999900001
user.app.account.for.shop.card.version2.new.user.password=123456
user.app.account.for.shop.card.version2.new.user.account.id=1398712902

user.app.account.for.shop.card.version2.new.user02.account=13999900003
user.app.account.for.shop.card.version2.new.user02.password=123456
user.app.account.for.shop.card.version2.new.user02.account.id=1398715012

user.app.account.for.shop.card.version2.new.user03.account=13999900002
user.app.account.for.shop.card.version2.new.user03.password=123456
user.app.account.for.shop.card.version2.new.user03.account.id=1398712910

user.app.account.for.shop.card.version2.new.user04.account=13999900004
user.app.account.for.shop.card.version2.new.user04.password=123456
user.app.account.for.shop.card.version2.new.user04.account.id=1398717234


# \u718A\u732B\u8054\u76DF\u6EE1\u51CF\u5238\u6D4B\u8BD5\u8D26\u53F7
user.app.account.for.shop.card.version2.pandaFull.user.account=17000001111
user.app.account.for.shop.card.version2.pandaFull.user.password=111111
user.app.account.for.shop.card.version2.pandaFull.user.account.id=1398713048
# \u718A\u732B\u8054\u76DF\u6298\u6263\u5238\u6D4B\u8BD5\u8D26\u53F7
user.app.account.for.shop.card.version2.pandaDiscount.user.account=17000001112
user.app.account.for.shop.card.version2.pandaDiscount.user.password=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id=1398713050
# \u718A\u732B\u8054\u76DFXMLM02\u6298\u6263\u5238\u6D4B\u8BD5\u8D26\u53F7
user.app.account.for.shop.card.version2.pandaDiscount.user.account.xmlm02=17000001113
user.app.account.for.shop.card.version2.pandaDiscount.user.password.xmlm02=111111
user.app.account.for.shop.card.version2.pandaDiscount.user.account.id.xmlm02=1398713062
# \u65E0\u4EFB\u4F55\u4F18\u60E0\u5238\u6D4B\u8BD5\u8D26\u53F7
user.app.account.for.shop.card.version2.no.coupon.user.account=17000001114
user.app.account.for.shop.card.version2.no.coupon.user.password=111111
user.app.account.for.shop.card.version2.no.coupon.user.account.id=1398713128
#\u4F1A\u5458\u7528\u6237
user.app.account.for.member.order.user.account=17000001115
user.app.account.for.member.order.user.password=111111
user.app.account.for.member.order.user.account.id=1398715264

user.app.for.test.shop.card.version2.pickup.discountSn=7231SWL74W
user.app.for.test.shop.card.version2.takeout.discountSn=7231NHOQPT
user.app.for.test.shop.card.version2.shop.new.user.discountSn=5452LGZTXY
user.app.for.test.shop.card.version2.voucherSn=54522NRAFJ
user.app.for.test.shop.card.version2.shop.first.discount.id=445

#\u4F1A\u5458\u7528\u6237
user.app.account.for.shop.card.version2.member.account=17048460003
user.app.account.for.shop.card.version2.member.password=123456a
user.app.account.for.shop.card.version2.member.cityname=\u4E5D\u6C5F\u5E02

#\u4F1A\u5458\u57CE\u5E02ID
user.app.for.test.shop.card.version2.memberCityId=1111378
#\u5E97\u94FA\u4F1A\u5458\u7EA2\u5305-\u5E97\u94FA\u8054\u76DF\u5238\u7EA2\u5305ID
user.app.for.test.shop.card.version2.shop.redPacketId=888892732

#\u65B0\u4EBA\u9996\u5355\u6807\u7B7E\u4EBA\u7FA4\u8D26\u53F7
user.app.account.for.shop.card.version2.first.order.user.password=123456
user.app.account.for.shop.card.version2.first.order.user.account1=15100000021
user.app.account.for.shop.card.version2.first.order.user.userId1=1398713060
user.app.account.for.shop.card.version2.first.order.user.account2=15100000022
user.app.account.for.shop.card.version2.first.order.user.userId2=1398713064
#\u65B0\u4EBA\u9996\u5355\u6807\u7B7E\u4EBA\u7FA4\u8BBE\u5907
user.app.account.for.shop.card.version2.first.order.user.distinctId=39830e1eff8d149a
user.app.account.for.shop.card.version2.first.order.user.distinctId2=2365086D-71E6-4761-9C6B-75234AEEB0BF
user.app.account.for.shop.card.version2.first.order.user.distinctId3=0D765882-E787-4729-A3FF-72A043B756DE
user.app.account.for.shop.card.version2.first.order.user.distinctId4=0D765882-E787-4729-A3FF-72A043B756D3

#\u62DB\u5546\u8BA1\u5212id
user.app.for.test.shop.card.version2.invitation.activity.id=1698

#\u81EA\u52A8\u5316\u6D4B\u8BD5\u5E97\u94FA\u5546\u5BB6\u6807\u7B7E
user.app.for.test.shop.card.version2.shop.category.id=[5946]
#\u5546\u5361\u8425\u4E1A\u72B6\u6001\u6D4B\u8BD5\u5E97\u94FA\u4FE1\u606F
user.app.for.test.shop.card.version2.shopId.close=345263066
user.app.for.test.shop.card.version2.shopId.stop.order=617846488
#\u5546\u5361\u53EF\u9884\u7EA6\u72B6\u6001\u5E97\u94FA
user.app.for.test.shop.card.version2.open.pre=855828829
user.app.for.test.shop.card.version2.open.no.pre=221864167
user.app.for.test.shop.card.version2.close.pre=422389118
user.app.for.test.shop.card.version2.close.no.pre=335765650
#\u65E5\u7167\u81EA\u52A8\u5316\u6D4B\u8BD5\u5E97\u94FA
user.app.for.test.shop.card.version3.shopId.sun=969518737

#\u5546\u5361\u7EA2\u5305\u6807\u7B7E\u6D4B\u8BD5\uFF08SKYX\u5B9E\u9A8C\u7EC4\uFF09
#\u5E97\u94FA\u7EA2\u5305\u5546\u5BB6 ID
user.app.for.test.shop.card.version3.shopId=456846660
#\u6EE1\u51CF\u52A0\u7801\u5546\u5BB6ID
user.app.for.test.shop.card.version3.increase.shopId=829805751
#\u6298\u6263\u52A0\u7801\u5546\u5BB6ID
user.app.for.test.shop.card.version3.increase.discount.shopId=768477723
#\u6709\u7EA2\u5305\u7684\u8D26\u53F7
user.app.for.test.shop.card.version3.account=19286819216
user.app.for.test.shop.card.version3.password=12345678
user.app.for.test.shop.card.version3.userId=1398717855
#\u795E\u5238\u7EA2\u5305Id
user.app.for.test.shop.card.version3.redpacketId=888893280
#\u8054\u76DF\u6EE1\u51CF\u5238id
user.app.for.test.shop.card.version3.redpacketId2=888895652
#\u8054\u76DF\u6298\u6263\u5238id
user.app.for.test.shop.card.version3.redpacketId3=888895653
#\u666E\u901A\u6EE1\u51CF\u5238\u7EA2\u5305id
user.app.for.test.shop.card.version3.redpacketId4=888895549
#\u666E\u901A\u6298\u6263\u5238\u7EA2\u5305id
user.app.for.test.shop.card.version3.redpacketId5=888895655
#\u6D4B\u8BD5\u6807\u7B7E\u6392\u5E8F\uFF0C\u975E\u4F1A\u5458\u8D26\u53F7
user.app.for.test.shop.card.version3.sort.account=13799900001
user.app.for.test.shop.card.version3.sort.password=12345678
user.app.for.test.shop.card.version3.sort.userId=1398719769
#\u6D4B\u8BD537\u6807\u7B7E\u6392\u5E8F\uFF0C\u4F1A\u5458\u8D26\u53F7
user.app.for.test.shop.card.version3.sort.member.account=13799900002
user.app.for.test.shop.card.version3.sort.member.password=12345678
user.app.for.test.shop.card.version3.sort.member.userId=1398719770
#\u6D4B\u8BD532\u6807\u7B7E\u6392\u5E8F\uFF0C\u4F1A\u5458\u8D26\u53F7
user.app.for.test.shop.card.version3.sort.member.account.32=13799900003
user.app.for.test.shop.card.version3.sort.member.account.32.password=12345678
user.app.for.test.shop.card.version3.sort.member.userId.32=1398719776
user.app.for.test.shop.card.version3.sort.member.shopId=475368440
#\u4F1A\u5458\u6298\u6263
user.app.for.test.shop.card.version3.sort.member.discount.shopId=221864167

########################################## \u5546\u5361\u4E8C\u671F\u6D4B\u8BD5\u6570\u636E-Stop # #########################################

# #########################################      panjuxiang\u4E2A\u4EBA\u6D4B\u8BD5\u6570\u636E   ###################################################
user.app.account.of.user.pjx.account=13990000001
user.app.account.of.user.pjx.password=123456
user.app.account.of.user.pjx.account.id=1398710856

user.app.account.of.user.pjx.account.02=13999900007
user.app.account.of.user.pjx.password.02=123456
user.app.account.of.user.pjx.account.id.02=1398717354

user.app.index.banner.index.module.detailId.type1=103457824
user.app.index.banner.index.module.detailId.type2=103458130
user.app.index.banner.index.module.detailId.type3=103457822
user.app.index.banner.index.module.detailId.type4=103458134
user.app.index.banner.index.module.detailId.type5=103458136
user.app.index.banner.index.module.detailId.type6=103458132
user.app.index.banner.index.module.detailId.type13=103458138
user.app.index.banner.index.module.detailId.type18=103457826
user.app.index.banner.index.module.detailId.type20=103458142
user.app.index.banner.index.module.detailId.type23=103458140
user.app.index.banner.index.module.detailId.oldUser=103458196
user.app.index.banner.index.module.detailId.newUser=103458194

user.app.for.test.shop.card.version2.highSaleNoTop10.shopId=772457447


user.app.game.newUser.account=13990000005
user.app.game.oldUser.account=13990000006
user.app.game.memberUser.account=13990000007
user.app.game.user.common.password=123456
user.app.game.sn01=4TuuyGqDa2tw


user.app.login.device.id = auto-test-device-id


# \u6D4B\u8BD5\u9884\u7B97\u5173\u8054\u7684\u9884\u7B97\u6D3B\u52A8sn
user.app.game.redPacket.activitySn.01=42528O72RJ

user.app.game.prizesId.redPacket.expire=6696
user.app.game.prizesId.redPacket.cancel=6698
user.app.game.prizesId.redPacket.noStock=6716
user.app.game.prizesId.redPacket.budgetBreak=6722
user.app.game.prizesId.redPacket.prizes.noStock=6724

# 测试会员折扣标签(type=44)，会员账号
user.app.for.test.shop.card.version3.vip.discount.account=13712340001
user.app.for.test.shop.card.version3.vip.discount.password=123456
# 测试会员折扣标签(type=44)，会员v2账号（level=2，2折）
user.app.for.test.shop.card.version3.vip.discount.v2.account=13712340002
user.app.for.test.shop.card.version3.vip.discount.v2.password=123456

#\u6768\u52E4\u52E4\u6D4B\u8BD5\u6570\u636E
#\u6709\u4F1A\u5458\u795E\u5238\u7528\u6237
user.app.account.for.shop.card.version2.godCoupon.account=17048460002
user.app.account.for.shop.card.version2.godCoupon.password=123456a
user.app.account.for.shop.card.version2.godCoupon.distinctId=ed99f8b03a64c6c1

#\u4E25\u707F\u707F\u6D4B\u8BD5\u6570\u636E
#\u666E\u901A\u8BA1\u5212\u8D26\u53F7
user.app.account.activity.user01.account=17700000002
user.app.account.activity.user01.password=123456
user.app.account.activity.user01.userId=140397134
#\u5F3A\u63A8\u8BA1\u5212\u8D26\u53F7
user.app.account.activity.user02.account=17700000001
user.app.account.activity.user02.password=123456
user.app.account.activity.user02.userId=1398661342
#\u667A\u80FD\u8425\u9500\u8D26\u53F7
user.app.account.activity.user03.account=17700000077
user.app.account.activity.user03.password=123456
user.app.account.activity.user03.userId=1398716814
