# 测试环境 数据库连接信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-3ns24734o9z8747d0jo.mysql.rds.aliyuncs.com:3306/panda_test
spring.datasource.username=panda_test
spring.datasource.password=Pan$te19*
#支付中心库
spring.datasource.pay.url=jdbc:mysql://rm-3ns24734o9z8747d0jo.mysql.rds.aliyuncs.com:3306/pandapay_test
# #########################################      以下是业务测试数据   ###################################################
# 统一登陆的密码
user.app.account.of.public.password=Test123456
user.app.account.of.public.login.type=2
# user002 是默认用户,用于测试订单主流程
user.app.account.of.user002.account.callingCode=86
user.app.account.of.user002.account=18711110002
user.app.account.of.user002.account.id=1398708422
# 设备号
user.app.account.of.user002.account.distinctId=44d6884fdb174a78

### 商卡二期测试数据
user.app.for.test.shop.card.version2.shopId=387549545
user.app.for.test.shop.card.version2.shopAccount=18722220010
user.app.for.test.shop.card.version2.shopPassword=415664VSC

#配送距离转换单位
user.app.server.metric.unit=km

#支付中心测试站域名
pay.server.notification.app.url.domain=https://hz-test-pay.hungrypanda.cn

# #########################################      panjuxiang个人测试数据   ###################################################
user.app.account.of.user.pjx.account=13990000001
user.app.account.of.user.pjx.password=123456
user.app.account.of.user.pjx.account.id=1398710856
user.app.index.banner.index.module.detailId.type3=103457822
user.app.index.banner.index.module.detailId.type1=103457824
user.app.index.banner.index.module.detailId.type18=103457826
user.app.index.banner.index.module.detailId.type2=103458130

# #########################################      panjuxiang个人测试数据   ###################################################
