# 测试环境 数据库连接信息
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-3ns24734o9z8747d0jo.mysql.rds.aliyuncs.com:3306/panda_test
spring.datasource.username=panda_test
spring.datasource.password=Pan$te19*

# #########################################      以下是业务测试数据   ###################################################
bdm.account.of.public.password=Test123456

