# 测试用例默认数据库链接信息，panda_test
datasource.url.panda_test=jdbc:mysql://hp-polar-test-business-master-pub.mysql.polardb.rds.aliyuncs.com:3306/panda_test
datasource.username.panda_test=panda_test
datasource.password.panda_test=Pan$te19*

# #########################################      以下是业务测试数据   ###################################################
bdm.account.of.public.password=Test123456

